force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <label>Estimated Time</label>
    <summarizedField>Unit__c.Estimated_Time__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <summarizedField>Unit__c.Points__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/ModuleResponse__c/ModuleResponse__c.object-meta.xml
<CustomObject>
    <label>ModuleResponse</label>
    <nameField>
        <label>ModuleResponse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ModulesResponse</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ModuleResponse__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>ModulesResponse</relationshipLabel>
    <relationshipName>ModulesResponse</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ModuleResponse__c/fields/Points_Achieved__c.field-meta.xml
<CustomField>
    <fullName>Points_Achieved__c</fullName>
    <label>Points Achieved</label>
    <summarizedField>UnitResponse__c.Points_Achieved__c</summarizedField>
    <summaryForeignKey>UnitResponse__c.ModuleResponse__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/ModuleResponse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ModuleResponse__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ModulesResponse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Options</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuestionResponse__c/QuestionResponse__c.object-meta.xml
<CustomObject>
    <label>QuestionResponse</label>
    <nameField>
        <label>QuestionResponse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QuestionResponses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuestionResponse__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>QuestionResponses</relationshipLabel>
    <relationshipName>QuestionResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuestionResponse__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>QuestionResponses</relationshipLabel>
    <relationshipName>QuestionResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuestionResponse__c/fields/UnitResponse__c.field-meta.xml
<CustomField>
    <fullName>UnitResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UnitResponse</label>
    <referenceTo>UnitResponse__c</referenceTo>
    <relationshipLabel>QuestionResponses</relationshipLabel>
    <relationshipName>QuestionResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trail__c/Trail__c.object-meta.xml
<CustomObject>
    <label>Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trail__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <label>Estimated Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trail_Module__c/Trail_Module__c.object-meta.xml
<CustomObject>
    <label>Trail-Module</label>
    <nameField>
        <label>Trail-Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trail-Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trail_Module__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <formula>Module__r.Estimated_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trail_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Trail-Modules</relationshipLabel>
    <relationshipName>Trail_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trail_Module__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>Module__r.Points__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trail_Module__c/fields/Trail__c.field-meta.xml
<CustomField>
    <fullName>Trail__c</fullName>
    <label>Trail</label>
    <referenceTo>Trail__c</referenceTo>
    <relationshipLabel>Trail-Modules</relationshipLabel>
    <relationshipName>Trail_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trail_Progress__c/Trail_Progress__c.object-meta.xml
<CustomObject>
    <label>Trail Progress</label>
    <nameField>
        <label>Trail Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trail Progress</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trail_Progress__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <formula>Completed_Modules__c / Amount_Of_Modules__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Trail_Progress__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trail_Progress__c/fields/Trail__c.field-meta.xml
<CustomField>
    <fullName>Trail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trail</label>
    <referenceTo>Trail__c</referenceTo>
    <relationshipLabel>Trail Progress</relationshipLabel>
    <relationshipName>Trail_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trail_Progress__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Trail_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <description>Estimated time in minutes</description>
    <inlineHelpText>Estimated time in minutes</inlineHelpText>
    <label>Estimated Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UnitResponse__c/UnitResponse__c.object-meta.xml
<CustomObject>
    <label>UnitResponse</label>
    <nameField>
        <label>UnitResponse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UnitResponses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitResponse__c/fields/Attempts__c.field-meta.xml
<CustomField>
    <fullName>Attempts__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Attempts</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UnitResponse__c/fields/ModuleResponse__c.field-meta.xml
<CustomField>
    <fullName>ModuleResponse__c</fullName>
    <label>ModuleResponse</label>
    <referenceTo>ModuleResponse__c</referenceTo>
    <relationshipLabel>UnitResponses</relationshipLabel>
    <relationshipName>UnitResponses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UnitResponse__c/fields/Points_Achieved__c.field-meta.xml
<CustomField>
    <fullName>Points_Achieved__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points Achieved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UnitResponse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UnitResponse__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>UnitResponses</relationshipLabel>
    <relationshipName>UnitResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitResponse__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UnitResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UnitService.cls
public class UnitService{
    
    public class UnitWrapper{
        @AuraEnabled
        public Unit__c unit; 
        @AuraEnabled
        public List<Question__c> questions;  //Listado de Preguntas con Opciones relacionadas
	}
    
    public class TrailWrapper{
        @AuraEnabled
        public Trail__c trail; 
        @AuraEnabled
        public Integer progressTrail; //Porcentaje de progreso del Alumno en el Trail
        @AuraEnabled
        public List<Module__c> modules; //Módulos con Unidades relacionadas
        @AuraEnabled
        public List<Id> passedModuleIds; //Ids de módulos relacionados al Trail actual en los que el Alumno ya aprobó
        @AuraEnabled
        public List<Id> passedUnitIds; //Ids de Unidades relacionadas a módulos del Trail actual que el Alumno ya aprobó
    }
    
    @AuraEnabled(cacheable=true)
    public static Boolean saveAnswers(Id unitId, Object jsonAnswers){
        // JSON.Serialize jsonAnswers before deserializing in order to make sure it's on proper format.
        // MAP(ID = QUESTION, ID = OPTION)
        Map<Id, Id> answerMap = (Map<Id, Id>) JSON.deserializeStrict(JSON.serialize(jsonAnswers), Map<Id, Id>.class);
        
        //Actual user
        User actualUser = [select Id from User where Id = :UserInfo.getUserId()];
        
        
        // First, we check if there was a previous unitResponse to this unit
        Integer Attempts = 1;
        List<UnitResponse__c> prevUnitResponse = [SELECT Id, Unit__c, User__c, Status__c, Points_Achieved__c, Attempts__c 
                                                  FROM UnitResponse__c 
                                                  WHERE User__c = :actualUser.Id AND Unit__c = :unitId AND Status__c = 'Fail'];
        if (prevUnitResponse.size() > 0){
            Attempts = prevUnitResponse.size() + 1;
        }
        
        // Creation of a response to the unit.
        UnitResponse__c unidadConRespuestas = new UnitResponse__c(Unit__c = unitId, Status__c = 'Draft', User__c = actualUser.Id, Attempts__c = Attempts);
        
        // Query the related module of the unit which comes by parameter.
        List<Unit__c> moduloConfig = [SELECT Id, Module__c FROM Unit__c WHERE Id = :unitId];
        
      	// Query to check if there is a ModuleResponse of the actual user and of the same module.
        List<ModuleResponse__c> userModulo = [SELECT Id FROM ModuleResponse__c WHERE Module__c = :moduloConfig[0].Module__c AND User__c = :actualUser.id];
        
		// If userModule does not exists, a ModuleResponse for that module should be created first.     
        if(userModulo.size() == 0){  
            ModuleResponse__c nuevoUserM = new ModuleResponse__c(Module__c = moduloConfig[0].Module__c, User__c = actualUser.Id, Status__c = 'In progress');
            insert nuevoUserM;    
            unidadConRespuestas.ModuleResponse__c = nuevoUserM.Id;
        }
        // If userModule does exists, I append the unit for that module 
        else{
            unidadConRespuestas.ModuleResponse__c = userModulo[0].Id;
        }
        upsert unidadConRespuestas; 
        
        
        // Creation of answers record for each answered question.
        List<QuestionResponse__c> unitResponses = new List<QuestionResponse__c>();
        
        for (Id questionId : answerMap.keySet()) {
            QuestionResponse__c unitResponse = new QuestionResponse__c(
                UnitResponse__c = unidadConRespuestas.Id,
                Question__c = questionId,
                Option__c = (Id)answerMap.get(questionId)
            );
            unitResponses.add(unitResponse);
        }
        insert unitResponses;
        
        // My UnitResponse object is now in "Answered" status
        unidadConRespuestas.Status__c = 'Answered';
        try{
            update unidadConRespuestas;
            if(unidadConRespuestas.Status__c == 'Success'){
                return true;
            }else{
                return false;
            }
        }catch(DmlException e){
            System.debug(e.getMessage());
            return false;
        }  
    }
    
    @AuraEnabled(cacheable=true)
    public static TrailWrapper getTrailWrapper(Id trailId){ // MÉTODO GET TRAIL WRAPPER
        // Actual User.
    	User actualUser = [select Id from User where Id = :UserInfo.getUserId()];
        
        // Creation of the wrapper that we will return.
        TrailWrapper wrapper = new TrailWrapper(); 
        
        List<Trail__c> theTrail = [SELECT Id, Name, Description__c, Estimated_Time__c, Points__c FROM Trail__c WHERE Id = :trailId];
        wrapper.trail = theTrail[0];
        
        List<Trail_Progress__c> trailProgress = [SELECT Id, Progress__c FROM Trail_Progress__c WHERE Trail__c = :trailId AND User__c = :actualUser.Id];
        if(trailProgress.size() == 0){
            wrapper.progressTrail = 0;
        }else{
        	wrapper.progressTrail = trailProgress[0].Progress__c.intValue();            
        }

        
        List<Trail_Module__c> trailModules = [SELECT Id, Trail__c, Module__c
                                              FROM Trail_Module__c
                                              WHERE Trail__c = :trailId];
        List<Id> listOfModuleIds = new List<Id>();
        for(Trail_Module__c tm : trailModules){
            listOfModuleIds.add(tm.Module__c);
        }
        // Modules related to the trail.
        List<Module__c> modules = [SELECT Id, Name, Estimated_Time__c, Description__c, Active__c, Roles__c, Skills__c, Points__c, Number_Of_Units__c,
                                   (SELECT Id, Name, Points__c, Estimated_Time__c FROM Units__r)
                                   FROM Module__c WHERE Id in :listOfModuleIds];
        wrapper.modules = modules;
        
        List<ModuleResponse__c> moduleResponses = [SELECT Id, (SELECT Id, Status__c, Unit__c FROM UnitResponses__r) 
                                                   FROM ModuleResponse__c 
                                                   WHERE Module__c in :modules AND User__c = :actualUser.id AND Status__c = 'Complete'];
        Set<Id> moduleResponseIds = new Set<Id>();
        for(ModuleResponse__c mr : moduleResponses){
            moduleResponseIds.add(mr.Id);
        }

        wrapper.passedModuleIds = new List<Id>(moduleResponseIds);
        
		// Units present in the modules of the trail.       
        List<Unit__c> units = [SELECT Id, Module__c, Name, Points__c, Estimated_Time__c, Content__c
                               FROM Unit__c
                               WHERE Module__c in :listOfModuleIds];
        
        // Set of ids of units
        Set<Id> unitsIds = new Set<Id>();
        for(Unit__c u : units){
            unitsIds.add(u.Id);
        }
        // UnitResponses list of this units.
        List<UnitResponse__c> UnitResponsesCorrect = [SELECT Id, Unit__c, Status__c FROM UnitResponse__c
                                                      WHERE Status__c = 'Success' AND Unit__c in :unitsIds];
        Set<Id> unitResponsesId = new Set<Id>();
        for(UnitResponse__c ur : UnitResponsesCorrect){
            unitResponsesId.add(ur.Unit__c);
        }
        
        // Unidades que el usuario respondio correctamente en el trail
        List<Unit__c> unitsCorrects = [SELECT Id FROM Unit__c WHERE Id in :unitResponsesId];
        List<Id> idCorrectUnits = new List<Id>();
        for(Unit__c u : unitsCorrects){
            idCorrectUnits.add(u.Id);
        }
        wrapper.passedUnitIds = idCorrectUnits;
        
        /*Set<Id> unitResponseIds = new Set<Id>();
        for(ModuleResponse__c mr : moduleResponses){
            for(UnitResponse__c ur : mr.UnitResponses__r){
                unitResponseIds.add(ur.Id);
            }
        }
        wrapper.passedUnitIds = new List<Id>(unitResponseIds);*/

        return wrapper;
    }
    
    @AuraEnabled(cacheable=true)
    public static UnitWrapper getUnitWrapper(Id unitId){
        // Creates a UnitWrapper object to return.
        UnitWrapper wrapper = new UnitWrapper();
        
        // Get the unit and assign it to the variable.
        Unit__c unit = [SELECT Id, Name, Points__c, Estimated_Time__c, Content__c, Module__c FROM Unit__c WHERE Id = :unitId];
        wrapper.unit = unit;
        
        List<Question__c> questions = [SELECT Id, Name, Description__c, Unit__c, (SELECT Id, Question__c, Description__c, isCorrect__c FROM Options__r)
                     				   FROM Question__c 
                                       WHERE Unit__c = :unitId];
        wrapper.questions = questions;                               
        
        return wrapper;
    }
}