force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <label>Estimated Time</label>
    <summarizedField>Unit__c.Estimated_Time__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <summarizedField>Unit__c.Points__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business User</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Marketer</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skills</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ModuleResponse__c/ModuleResponse__c.object-meta.xml
<CustomObject>
    <label>ModuleResponse</label>
    <nameField>
        <label>ModuleResponse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ModulesResponse</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ModuleResponse__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>ModulesResponse</relationshipLabel>
    <relationshipName>ModulesResponse</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ModuleResponse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ModuleResponse__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ModulesResponse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Option__c/fields/isCorrect__c.field-meta.xml
<CustomField>
    <fullName>isCorrect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCorrect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Options</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuestionResponse__c/QuestionResponse__c.object-meta.xml
<CustomObject>
    <label>QuestionResponse</label>
    <nameField>
        <label>QuestionResponse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QuestionResponses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuestionResponse__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>QuestionResponses</relationshipLabel>
    <relationshipName>QuestionResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuestionResponse__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>QuestionResponses</relationshipLabel>
    <relationshipName>QuestionResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuestionResponse__c/fields/UnitResponse__c.field-meta.xml
<CustomField>
    <fullName>UnitResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UnitResponse</label>
    <referenceTo>UnitResponse__c</referenceTo>
    <relationshipLabel>QuestionResponses</relationshipLabel>
    <relationshipName>QuestionResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trail__c/Trail__c.object-meta.xml
<CustomObject>
    <label>Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trail__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <label>Estimated Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trail_Module__c/Trail_Module__c.object-meta.xml
<CustomObject>
    <label>Trail-Module</label>
    <nameField>
        <label>Trail-Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trail-Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trail_Module__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <formula>Module__r.Estimated_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trail_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Trail-Modules</relationshipLabel>
    <relationshipName>Trail_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trail_Module__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>Module__r.Points__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trail_Module__c/fields/Trail__c.field-meta.xml
<CustomField>
    <fullName>Trail__c</fullName>
    <label>Trail</label>
    <referenceTo>Trail__c</referenceTo>
    <relationshipLabel>Trail-Modules</relationshipLabel>
    <relationshipName>Trail_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trail_Progress__c/Trail_Progress__c.object-meta.xml
<CustomObject>
    <label>Trail Progress</label>
    <nameField>
        <label>Trail Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trail Progress</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trail_Progress__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trail_Progress__c/fields/Trail__c.field-meta.xml
<CustomField>
    <fullName>Trail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trail</label>
    <referenceTo>Trail__c</referenceTo>
    <relationshipLabel>Trail Progress</relationshipLabel>
    <relationshipName>Trail_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trail_Progress__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Trail_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>Content of the unit.</description>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <description>Estimated time in minutes</description>
    <inlineHelpText>Estimated time in minutes</inlineHelpText>
    <label>Estimated Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UnitResponse__c/UnitResponse__c.object-meta.xml
<CustomObject>
    <label>UnitResponse</label>
    <nameField>
        <label>UnitResponse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UnitResponses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitResponse__c/fields/ModuleResponse__c.field-meta.xml
<CustomField>
    <fullName>ModuleResponse__c</fullName>
    <label>ModuleResponse</label>
    <referenceTo>ModuleResponse__c</referenceTo>
    <relationshipLabel>UnitResponses</relationshipLabel>
    <relationshipName>UnitResponses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UnitResponse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UnitResponse__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>UnitResponses</relationshipLabel>
    <relationshipName>UnitResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitResponse__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UnitResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UnitServiceTest.cls
@isTest
public class UnitServiceTest {

    @isTest
    private static void firstTestMethod(){
        
        User testUser = [select Id from User where Id = :UserInfo.getUserId()];
        
        Module__c module = new Module__c(
            Name = 'PrimerModuloTest',
            Roles__c = 'Admin',
            Skills__c = 'Apex'
        );
        insert module;
        
        Unit__c unit = new Unit__c(
        	Module__c = module.id,
            Points__c = 100,
            Content__c = 'First unit content',
            Estimated_Time__c = 20
        );
        insert unit;
        
        Question__c question = new Question__c(
            Unit__c = unit.id,
            Description__c = 'Question description, the real question'
        );
        insert question;
        
        Option__c option = new Option__c(
            Question__c = question.id,
            Description__c = 'Option descrition, the real option',
            isCorrect__c = true
        );
        insert option;
        
        QuestionResponse__c questionResponse = new QuestionResponse__c(
            Question__c = question.id,
            Option__c = option.id
        );
        insert questionResponse;

        
        Map<Id, Id> jsonAnswers = new Map<Id, Id>();
        jsonAnswers.put(question.id, option.id);
        
        Object testAnswers = jsonAnswers;
        
        test.startTest();
        Boolean result = UnitService.saveAnswers(unit.Id, testAnswers);
        test.stopTest();
        
        System.assertEquals(true, result);
        List<UnitResponse__c> unitResponses = [SELECT Id, Status__c FROM UnitResponse__c WHERE Unit__c = :unit.Id];
        System.assertEquals(1, unitResponses.size());
        System.assertEquals('Success', unitResponses[0].Status__c);
        
        List<QuestionResponse__c> questionResponses = [SELECT Id, Question__c, Option__c FROM QuestionResponse__c WHERE UnitResponse__c = :unitResponses[0].Id];
        System.assertEquals(1, questionResponses.size());
        System.assertEquals(question.Id, questionResponses[0].Question__c);
        System.assertEquals(option.Id, questionResponses[0].Option__c);
    }
   
    @isTest
    private static void secondTestMethod(){
        
        User testUser = [select Id from User where Id = :UserInfo.getUserId()];
        
        Module__c module = new Module__c(
            Name = 'PrimerModuloTest',
            Roles__c = 'Admin',
            Skills__c = 'Apex'
        );
        insert module;
        
        Unit__c unit = new Unit__c(
        	Module__c = module.id,
            Points__c = 100,
            Content__c = 'First unit content',
            Estimated_Time__c = 20
        );
        insert unit;
        
        Question__c question = new Question__c(
            Unit__c = unit.id,
            Description__c = 'Question description, the real question'
        );
        insert question;
        
        Option__c option = new Option__c(
            Question__c = question.id,
            Description__c = 'Option descrition, the real option',
            isCorrect__c = true
        );
        insert option;
        
        ModuleResponse__c moduleResponse = new ModuleResponse__c(
            Module__c = module.id,
            User__c = testUser.id
        );
        insert moduleResponse;
        
        QuestionResponse__c questionResponse = new QuestionResponse__c(
            Question__c = question.id,
            Option__c = option.id
        );
        insert questionResponse;

        
        Map<Id, Id> jsonAnswers = new Map<Id, Id>();
        jsonAnswers.put(question.id, option.id);
        
        Object testAnswers = jsonAnswers;
        
        test.startTest();
        Boolean result = UnitService.saveAnswers(unit.Id, testAnswers);
        test.stopTest();
        
        System.assertEquals(true, result);
        List<UnitResponse__c> unitResponses = [SELECT Id, Status__c FROM UnitResponse__c];
        System.assertEquals(1, unitResponses.size());
        System.assertEquals('Success', unitResponses[0].Status__c);
        
        List<QuestionResponse__c> questionResponses = [SELECT Id, Question__c, Option__c FROM QuestionResponse__c WHERE UnitResponse__c = :unitResponses[0].Id];
        System.assertEquals(1, questionResponses.size());
        System.assertEquals(question.Id, questionResponses[0].Question__c);
        System.assertEquals(option.Id, questionResponses[0].Option__c);
    }

    @isTest
    private static void thirdTestMethod(){
        
        User testUser = [select Id from User where Id = :UserInfo.getUserId()];
        
        Module__c module = new Module__c(
            Name = 'PrimerModuloTest',
            Roles__c = 'Admin',
            Skills__c = 'Apex'
        );
        insert module;
        
        Unit__c unit = new Unit__c(
        	Module__c = module.id,
            Points__c = 100,
            Content__c = 'First unit content',
            Estimated_Time__c = 20
        );
        insert unit;
        
        Question__c question = new Question__c(
            Unit__c = unit.id,
            Description__c = 'Question description, the real question'
        );
        insert question;
        
        Option__c option = new Option__c(
            Question__c = question.id,
            Description__c = 'Option descrition, the real option',
            isCorrect__c = true
        );
        insert option;
        
        Option__c wrongOption = new Option__c(
            Question__c = question.id,
            Description__c = 'Option descrition, the real incorrect option',
            isCorrect__c = false
        );
        insert wrongOption;
        
        ModuleResponse__c moduleResponse = new ModuleResponse__c(
            Module__c = module.id,
            User__c = testUser.id
        );
        insert moduleResponse;
        
        QuestionResponse__c questionResponse = new QuestionResponse__c(
            Question__c = question.id,
            Option__c = wrongOption.id
        );
        insert questionResponse;

        
        Map<Id, Id> jsonAnswers = new Map<Id, Id>();
        jsonAnswers.put(question.id, wrongOption.id);
        
        Object testAnswers = jsonAnswers;
        
        test.startTest();
        Boolean result = UnitService.saveAnswers(unit.Id, testAnswers);
        test.stopTest();
        
        System.assertEquals(true, result);
        List<UnitResponse__c> unitResponses = [SELECT Id, Status__c FROM UnitResponse__c];
        System.assertEquals(1, unitResponses.size());
        System.assertEquals('Fail', unitResponses[0].Status__c);
        
        List<QuestionResponse__c> questionResponses = [SELECT Id, Question__c, Option__c FROM QuestionResponse__c WHERE UnitResponse__c = :unitResponses[0].Id];
        System.assertEquals(1, questionResponses.size());
        System.assertEquals(question.Id, questionResponses[0].Question__c);
        System.assertEquals(wrongOption.Id, questionResponses[0].Option__c);
    }
    
    @isTest
    private static void testWrappers(){
        User testUser = [select Id from User where Id = :UserInfo.getUserId()];
        
        Trail__c trail = new Trail__c(
            Name = 'Primer trail',
            Description__c = 'Una desc'
        );
        insert trail;
        
        Trail_Progress__c trailProgress = new Trail_Progress__c(
            User__c = testUser.Id,
            Trail__c = trail.id
        );
        insert trailProgress;
        
        Module__c module = new Module__c(
            Name = 'PrimerModuloTest',
            Roles__c = 'Admin',
            Skills__c = 'Apex',
            Active__c = true
        );
        insert module;
        
        Trail_Module__c trailModule = new Trail_Module__c(
            Trail__c = trail.id,
            Module__c = module.id
        );
        insert trailModule;
        
        Unit__c unit = new Unit__c(
            Module__c = module.id,
            Points__c = 100,
            Content__c = 'First unit content',
            Estimated_Time__c = 20
        );
        insert unit;
        
        Question__c question = new Question__c(
            Unit__c = unit.id,
            Description__c = 'Question description, the real question'
        );
        insert question;
        
        Option__c option = new Option__c(
            Question__c = question.id,
            Description__c = 'Option descrition, the real option',
            isCorrect__c = true
        );
        insert option;
        
        ModuleResponse__c moduleResponse = new ModuleResponse__c(
            Module__c = module.id,
            User__c = testUser.id,
            Status__c = 'Complete'
        );
        insert moduleResponse;
        
        UnitResponse__c unitResponse = new UnitResponse__c(
            ModuleResponse__c = moduleResponse.id,
            Unit__c = unit.id,
            Status__c = 'Success'
        );
        insert unitResponse;
        
        Test.startTest();
        UnitService.TrailWrapper tw = UnitService.getTrailWrapper(trail.id);
        UnitService.UnitWrapper uw = UnitService.getUnitWrapper(unit.Id);
        Test.stopTest();
        
        System.assert(tw != null);
        System.assertEquals('Primer trail', tw.trail.Name);
        System.assert(uw != null);
    }
        
}