force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <label>Estimated Time</label>
    <summarizedField>Unit__c.Estimated_Time__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <summarizedField>Unit__c.Points__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Option__c/fields/isCorrect__c.field-meta.xml
<CustomField>
    <fullName>isCorrect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCorrect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Options</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuestionResponse__c/QuestionResponse__c.object-meta.xml
<CustomObject>
    <label>QuestionResponse</label>
    <nameField>
        <label>QuestionResponse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QuestionResponses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuestionResponse__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>QuestionResponses</relationshipLabel>
    <relationshipName>QuestionResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuestionResponse__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>QuestionResponses</relationshipLabel>
    <relationshipName>QuestionResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuestionResponse__c/fields/UnitResponse__c.field-meta.xml
<CustomField>
    <fullName>UnitResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UnitResponse</label>
    <referenceTo>UnitResponse__c</referenceTo>
    <relationshipLabel>QuestionResponses</relationshipLabel>
    <relationshipName>QuestionResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>Content of the unit.</description>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <description>Estimated time in minutes</description>
    <inlineHelpText>Estimated time in minutes</inlineHelpText>
    <label>Estimated Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UnitResponse__c/UnitResponse__c.object-meta.xml
<CustomObject>
    <label>UnitResponse</label>
    <nameField>
        <label>UnitResponse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UnitResponses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UnitResponse__c/fields/Attempts__c.field-meta.xml
<CustomField>
    <fullName>Attempts__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Attempts</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UnitResponse__c/fields/Points_Achieved__c.field-meta.xml
<CustomField>
    <fullName>Points_Achieved__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points Achieved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UnitResponse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UnitResponse__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>UnitResponses</relationshipLabel>
    <relationshipName>UnitResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnitResponse__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UnitResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UnitResponseService.cls
public class UnitResponseService {
    public static void checkResponses(List<UnitResponse__c> unitResponses){
        // Lista de Ids de unidades en las UnitsReponses que vienen por parámetro
        List<Id> unitsId = new List<Id>();
        for(UnitResponse__c u : unitResponses){
            unitsId.add(u.Unit__c);
        }
        
        // Map of units
        Map<Id, Unit__c> unitsMap = new Map<Id, Unit__c>();
        List<Unit__c> units = [SELECT Id, Points__c, Name, Estimated_Time__c, Module__c, Content__c FROM Unit__c WHERE Id in :unitsId];
        for(Unit__c u : units){
            unitsMap.put(u.Id, u);
        }
       
        // Quereamos las preguntas que estan en estas unidades(units) con su respuesta correctas
        List<Question__c> questions = [SELECT Id, (SELECT Id, isCorrect__c FROM Options__r WHERE isCorrect__c = true)
                                       FROM Question__c
                                       WHERE Unit__c in :unitsId];
              
        // Mapa de preguntas con sus respuestas correctas.
        // Map<ID = Question__c, ID = Options__c CORRECTA>;
        Map<Id, Id> questionOptionsMap = new Map<Id, Id>();
        // Loop through questions and their related options to populate the map.
        for (Question__c q : questions) {
            questionOptionsMap.put(q.Id, q.Options__r[0].Id);
        }
        
        // Quereamos todas las questionsResponse que vienen dentro de la lista de las unitResponses
        List<QuestionResponse__c> qr = [SELECT Id, Option__c, UnitResponse__c, Question__c
                                        FROM QuestionResponse__c
                                        WHERE UnitResponse__c in :unitResponses];
        
        // Mapa de Unidades respondidas del usuario con sus respectivas respuestas.
        Map<UnitResponse__c, List<QuestionResponse__c>> UnitWithQuestions = new Map<UnitResponse__c, List<QuestionResponse__c>>();
        for(UnitResponse__c ur : unitResponses){
            List<QuestionResponse__c> listOfResponses = new List<QuestionResponse__c>();
            for(QuestionResponse__c questionResponses : qr){
                if(questionResponses.UnitResponse__c == ur.Id){
                    listOfResponses.add(questionResponses);
                }
            }
            UnitWithQuestions.put(ur, listOfResponses);
        }
        
        // Ahora vemos si las respuetas a la unidad respondida por el usuario son correctas.
        for(UnitResponse__c ur : UnitWithQuestions.keySet()){
            List<QuestionResponse__c> responsesToUnit = UnitWithQuestions.get(ur);
            Boolean isUnitCorrect = true;
            for(QuestionResponse__c response : responsesToUnit){
                if(response.Option__c != questionOptionsMap.get(response.Question__c)){
                    isUnitCorrect = false;
                }
            }
            if(isUnitCorrect){
            	ur.Status__c = 'Success';
                Integer unitPoints = Integer.valueOf(unitsMap.get(ur.Unit__c).Points__c);
                if(ur.Attempts__c == 1){
                    ur.Points_Achieved__c = unitPoints;
                }else if(ur.Attempts__c == 2){
                    ur.Points_Achieved__c = (unitPoints / 2);
                }else if(ur.Attempts__c > 2){
                    ur.Points_Achieved__c = (unitPoints / 4);
                }
            }else{
                ur.Status__c = 'Fail';
            }
        }
        
    }
    
    public static void checkPointsUser(List<UnitResponse__c> unitResponses){
        Set<Id> unitResponsesIds = new Set<Id>();
        for (UnitResponse__c ur : unitResponses){
            unitResponsesIds.add(ur.Id);
        }

        List<UnitResponse__c> urSuccess = [SELECT Id, Points_Achieved__c, User__c, Status__c FROM UnitResponse__c WHERE Status__c = 'Success' AND Id in :unitResponsesIds];
        
        Set<Id> userIds = new Set<Id>();
        for (UnitResponse__c us : urSuccess){
            userIds.add(us.User__c);
        }
        
        List<User> users = [SELECT Id, Name, Score__c FROM User WHERE Id in :userIds];
        
        for (UnitResponse__c urS : urSuccess){
            for (User Us : users) {
                if (urS.User__c == us.Id){
                    if(Us.Score__c == null){
                        Us.Score__c = 0;
                    }
                    Us.Score__c = Us.Score__c + urS.Points_Achieved__c;
                }
            }
        }
        Update users;
    }
}